version: "3"
services:
  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - "backend"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/go/src/go-chat/backend
    ports:
      - "9090:9090"
    container_name: "backend"

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./client/src:/client/src
  #     - ./client/public:/client/public
  #   ports:
  #     - "5173:5173"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    ports:
      - "3000:3000"
  
  redis:
    image: redis
    ports:
     - "6379:6379"