// protoのバージョンの宣言

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: chat.proto

// packageの宣言

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChatService_GetRooms_FullMethodName       = "/pb.ChatService/GetRooms"
	ChatService_HelloBiStreams_FullMethodName = "/pb.ChatService/HelloBiStreams"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	GetRooms(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Rooms, error)
	HelloBiStreams(ctx context.Context, opts ...grpc.CallOption) (ChatService_HelloBiStreamsClient, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) GetRooms(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Rooms, error) {
	out := new(Rooms)
	err := c.cc.Invoke(ctx, ChatService_GetRooms_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) HelloBiStreams(ctx context.Context, opts ...grpc.CallOption) (ChatService_HelloBiStreamsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], ChatService_HelloBiStreams_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceHelloBiStreamsClient{stream}
	return x, nil
}

type ChatService_HelloBiStreamsClient interface {
	Send(*ChatMessageForSending) error
	Recv() (*ChatMessageForReceiving, error)
	grpc.ClientStream
}

type chatServiceHelloBiStreamsClient struct {
	grpc.ClientStream
}

func (x *chatServiceHelloBiStreamsClient) Send(m *ChatMessageForSending) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServiceHelloBiStreamsClient) Recv() (*ChatMessageForReceiving, error) {
	m := new(ChatMessageForReceiving)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility
type ChatServiceServer interface {
	GetRooms(context.Context, *emptypb.Empty) (*Rooms, error)
	HelloBiStreams(ChatService_HelloBiStreamsServer) error
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (UnimplementedChatServiceServer) GetRooms(context.Context, *emptypb.Empty) (*Rooms, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRooms not implemented")
}
func (UnimplementedChatServiceServer) HelloBiStreams(ChatService_HelloBiStreamsServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloBiStreams not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_GetRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetRooms(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_HelloBiStreams_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).HelloBiStreams(&chatServiceHelloBiStreamsServer{stream})
}

type ChatService_HelloBiStreamsServer interface {
	Send(*ChatMessageForReceiving) error
	Recv() (*ChatMessageForSending, error)
	grpc.ServerStream
}

type chatServiceHelloBiStreamsServer struct {
	grpc.ServerStream
}

func (x *chatServiceHelloBiStreamsServer) Send(m *ChatMessageForReceiving) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServiceHelloBiStreamsServer) Recv() (*ChatMessageForSending, error) {
	m := new(ChatMessageForSending)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRooms",
			Handler:    _ChatService_GetRooms_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HelloBiStreams",
			Handler:       _ChatService_HelloBiStreams_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat.proto",
}
