/**
 * @fileoverview gRPC-Web generated client stub for pb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: chat.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as chat_pb from './chat_pb'; // proto import: "chat.proto"


export class ChatServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetRooms = new grpcWeb.MethodDescriptor(
    '/pb.ChatService/GetRooms',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    chat_pb.Rooms,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    chat_pb.Rooms.deserializeBinary
  );

  getRooms(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<chat_pb.Rooms>;

  getRooms(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chat_pb.Rooms) => void): grpcWeb.ClientReadableStream<chat_pb.Rooms>;

  getRooms(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chat_pb.Rooms) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.ChatService/GetRooms',
        request,
        metadata || {},
        this.methodDescriptorGetRooms,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.ChatService/GetRooms',
    request,
    metadata || {},
    this.methodDescriptorGetRooms);
  }

}

