/**
 * @fileoverview gRPC-Web generated client stub for pb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: chat.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as chat_pb from './chat_pb'; // proto import: "chat.proto"


export class ChatServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetRooms = new grpcWeb.MethodDescriptor(
    '/pb.ChatService/GetRooms',
    grpcWeb.MethodType.UNARY,
    chat_pb.GetRoomsRequest,
    chat_pb.GetRoomsResponse,
    (request: chat_pb.GetRoomsRequest) => {
      return request.serializeBinary();
    },
    chat_pb.GetRoomsResponse.deserializeBinary
  );

  getRooms(
    request: chat_pb.GetRoomsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<chat_pb.GetRoomsResponse>;

  getRooms(
    request: chat_pb.GetRoomsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chat_pb.GetRoomsResponse) => void): grpcWeb.ClientReadableStream<chat_pb.GetRoomsResponse>;

  getRooms(
    request: chat_pb.GetRoomsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chat_pb.GetRoomsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.ChatService/GetRooms',
        request,
        metadata || {},
        this.methodDescriptorGetRooms,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.ChatService/GetRooms',
    request,
    metadata || {},
    this.methodDescriptorGetRooms);
  }

  methodDescriptorCreateChatMessage = new grpcWeb.MethodDescriptor(
    '/pb.ChatService/CreateChatMessage',
    grpcWeb.MethodType.UNARY,
    chat_pb.CreateChatMessageRequest,
    chat_pb.CreateChatMessageResponse,
    (request: chat_pb.CreateChatMessageRequest) => {
      return request.serializeBinary();
    },
    chat_pb.CreateChatMessageResponse.deserializeBinary
  );

  createChatMessage(
    request: chat_pb.CreateChatMessageRequest,
    metadata?: grpcWeb.Metadata | null): Promise<chat_pb.CreateChatMessageResponse>;

  createChatMessage(
    request: chat_pb.CreateChatMessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chat_pb.CreateChatMessageResponse) => void): grpcWeb.ClientReadableStream<chat_pb.CreateChatMessageResponse>;

  createChatMessage(
    request: chat_pb.CreateChatMessageRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chat_pb.CreateChatMessageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.ChatService/CreateChatMessage',
        request,
        metadata || {},
        this.methodDescriptorCreateChatMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.ChatService/CreateChatMessage',
    request,
    metadata || {},
    this.methodDescriptorCreateChatMessage);
  }

  methodDescriptorGetChatMessageStream = new grpcWeb.MethodDescriptor(
    '/pb.ChatService/GetChatMessageStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    chat_pb.GetChatMessageRequest,
    chat_pb.GetChatMessageResponse,
    (request: chat_pb.GetChatMessageRequest) => {
      return request.serializeBinary();
    },
    chat_pb.GetChatMessageResponse.deserializeBinary
  );

  getChatMessageStream(
    request: chat_pb.GetChatMessageRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<chat_pb.GetChatMessageResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/pb.ChatService/GetChatMessageStream',
      request,
      metadata || {},
      this.methodDescriptorGetChatMessageStream);
  }

}

